language: node_js
node_js:
  - '10'
  - '12'
after_success: npm run coverage
notifications:
  email:
    recipients:
      - post@kjellmorten.no
    on_success: never # default: change
    on_failure: always # default: always
